version: '{build}'

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - cmd: choco install ant -y -f -i
  - cmd: refreshenv
  - cmd: echo -Djna.nosys=true > .buckjavaargs.local
  - cmd: set GOROOT=
  - cmd: set PATH=%PATH:C:\go\bin;=%
  - cmd: set PATH=%PATH:C:\go\bin=%
  - cmd: set ANT_OPTS=-Xmx512m
  - cmd: set
  - cmd: python --version
  - cmd: java -version
  - cmd: ant -version

# to disable automatic builds by MsBuild
build: off

build_script:
  - "ant"
#  - "pwd" Ů /c/projects/hellowappveyor
  - "dir ."
  - "dir src"
  - "dir build"
  - "dir dist"
  - "cd build"
  - "dir ."
  - "cd classes"
  - "dir ."
  - "cd hello"
  - "dir ."
  - "Java Hello.class"
